### ISSUE TITLE
Uncaught TypeError: Cannot read property 'error' of undefined

### ISSUE THREAD

**Issue by steve13814** [codingbelief/atom-gtags#1]
Hi,
Your package is really helpful. It helps me to switch from sublime to atom.

But There's a small bug when there's no tag file in any project directory and I use Alt+1 to get definition. In the developer console I got this message:

Uncaught TypeError:  /home/user/code/git/atom-gtags/lib/main.coffee:350
Cannot read property 'error' of undefined

And this is caused by an undefined variable, and can be fixed by the following diff.

diff --git a/lib/gtags-symbols.coffee b/lib/gtags-symbols.coffee
index 24ea614..c21114f 100644
--- a/lib/gtags-symbols.coffee
+++ b/lib/gtags-symbols.coffee
@@ -93,6 +93,7 @@ class GtagsSymbols
       gtagsCommand: (options, arg) ->
         syms = []
         stas = {}
    +    status = {}
         paths = atom.project.getPaths()
         for path in paths
           if @hasTagsFile(path)

**Comment by codingbelief** [comment]
Thanks for the patch. :)
