### ISSUE TITLE
"alt-4 : Look up symbol definition in the project" doesn't work

### ISSUE THREAD

**Issue by fabio-porcedda** [codingbelief/atom-gtags#7]
First, thanks for this great atom package, it is really useful.

I've a problem, when i use the keyboard shortcut "alt+4" or "Atom Gtags: Lookup Definition" in the command palette, it doesn't find anything, it says "No matches found".

Instead the feature "alt-3 : List all symbols of the file" works fine.
I'm doing something wrong or it's a bug?

Thanks

**Comment by codingbelief** [comment]
It's a bug. It will be fixed in next release soon. Thanks for the feedback.

**Comment by fabio-porcedda** [comment]
Great!

Thanks

**Comment by codingbelief** [comment]
"Lookup Definition" requires at least 3 letters as prefix to trigger searching. Try type in definition prefix to the input box.
